### ISSUE TITLE
Feature: Account Login

### ISSUE THREAD

**Issue by sadhanavadrevu** [cs130-w22/Group-A1#1]
## Epic
As a user, I want to be able to create an account or login to my existing account so that I can see my invited events or create an event.

## User Stories
- [x] [Account Login](https://github.com/cs130-w22/Group-A1/issues/14)
- [x] [Account Creation](https://github.com/cs130-w22/Group-A1/issues/13)
- [x] ~As a user, I want to be able to login as a guest without creating an account.~
