### ISSUE TITLE
Feature: Event Creation

### ISSUE THREAD

**Issue by elyseyao** [cs130-w22/Group-A1#11]
## User Story
As an event owner, I want to be able to name and create an event so I can invite people.

## Detailed Description
Users should be able to create and save an event with a name, creation date, creator's user ID, and a unique generated alphanumeric URL, and the creator should be added as a member of the event. 

## Tasks
- [x] Event creation page (Kaitlyn)
- [x] Event creation API (Alvin)
- [x] Event data model/schema (Alvin)
- [x] Integrating front-end/back-end (Alvin)
