### ISSUE TITLE
Feature: Account Creation

### ISSUE THREAD

**Issue by elyseyao** [cs130-w22/Group-A1#13]
## User Story
 As a user, I want to be able to create an account so that I can create events.

## Detailed Description
Users should be able to create an account with a username and password. 

## Tasks 
- [x] User creation API (Elyse)
- [x] User data model/schema (Elyse)
- [x] Session management (Sadhna)
- [x] Signup page (Erdi)
- [x] Integrate front-end/back-end (Elyse)

## Acceptance Criteria
- [x] Given the user doesn't enter a username or password, they will be shown an error.
- [x] Given the user enters a username already in use, they will be shown an error.
- [x] Given the user enter a valid username and a password, an account will be created and they will be redirected to the main page.
