### ISSUE TITLE
Feature: Login

### ISSUE THREAD

**Issue by elyseyao** [cs130-w22/Group-A1#14]
## User Story
 As a user, I want to be able to login to my existing account so that I can view events that I have been invited to or to create an event.

## Detailed Description
Users should be able to login to their account with the correct username and password

## Tasks 
- [x] User login API (Elyse)
- [x] Session management (Sadhna)
- [x] Login page (Erdi)
- [x] Integrate front-end/back-end (Elyse)

## Acceptance Criteria
- [x] Given the user doesn't enter a username or password, they will be shown an error.
- [x] Given the user enters an invalid username or password, they will be shown an error.
- [x] Given the user enters a valid username and password, they will be logged in and redirected to the main page.
