### ISSUE TITLE
Feature: Create Polls

### ISSUE THREAD

**Issue by elyseyao** [cs130-w22/Group-A1#17]
## User Story
As a user, I want to be able to create a poll so that the group can vote on different things.

## Detailed Description
The user should be able to name and create a poll.

## Tasks
- [x] Add Polls section/Create a Poll button to the [event page](https://github.com/cs130-w22/Group-A1/issues/16)
- [x] Poll creation interface (e.g. a modal)
- [x] Poll backend API @elyseyao 
- [x] Poll data model/schema @elyseyao 

## Acceptance Criteria
- [x] Given I click on the Create a Poll button, then I should be shown an interface to create a new poll
- [x] Given I finish creating a poll, I should be redirected to the event page
- [x] Given I am on the event page, I should be able to see polls I have created
- [x] Given I enter an empty name for the poll, then I should be shown a validation error
