### ISSUE TITLE
Feature: Poll Voting

### ISSUE THREAD

**Issue by elyseyao** [cs130-w22/Group-A1#18]
## User Story
As a user, I want to be able to vote in polls so that I can choose my favorite option.

## Detailed Description
Users should be able to add their votes to a selected poll. 

After a user votes, the poll display should be updated with the number of votes per option and display them in descending order of votes. Whether by hovering, toggles, or some other way, the options should also show who voted on them.

## Tasks
- [x] Poll display frontend (can split this if necessary)
- [x] Poll voting API
- [x] Integration

## Acceptance Criteria
- [x] Given a user votes on a poll option, the number of votes should increment and their name should be displayed as a voter for that option.
- [x] Given that the poll options have different numbers of votes, they should be sorted in descending order of votes.
- [x] Given the option has votes, interacting with it should display the list of people who voted on it.
- [x] Given that the user removes their vote, the number of votes should decrement and their name should be removed as a voter for that option.
