### ISSUE TITLE
Feature: Select Availability

### ISSUE THREAD

**Issue by elyseyao** [cs130-w22/Group-A1#20]
## User Story
As a user, I want to input my availability for an event so people can know when I'm free.

## Detailed Description
Users should be able to select the dates and times that they are free.

## Tasks
- [x] Availability selector frontend
- [x] Availability selection API 
- [x] Integration

## Acceptance Criteria
- [x] Given that the user already has an availability selected, then they should be able to modify their selection.
- [x] Given that the user selects an availability, then their availability for the event should be updated.
- [x]  Given the user is an event participant, they should only be shown times within the owner-configured time range to schedule.
