### ISSUE TITLE
Feature: Event Configuration

### ISSUE THREAD

**Issue by elyseyao** [cs130-w22/Group-A1#25]
## User Story
As a group creator, I would like to be able to edit my event.

## Detailed Description
The creator should have access to an edit button that takes them into a configuration page with options to edit the event name and description and delete their event.

## Tasks
- [x] Edit event API
- [x] Delete event API
- [x] Edit event front-end

## Acceptance Criteria
- [x] Given I am a event owner, I should be able to edit my created event.
- [x] Given I edit and save my event details, they should be updated on the event page.
- [x] Given I delete my event, it should no longer be available for any user.
- [x] Given I try to set an empty title, I should be shown a validation error.
