### ISSUE TITLE
Feature: Poll Voting Limits

### ISSUE THREAD

**Issue by elyseyao** [cs130-w22/Group-A1#26]
## User Story
As a group owner, I would like to set a limit on how many times each member can vote on each poll.

## Detailed Description
By default, each user has an unlimited number of votes and can vote on as many options as possible. The group owner can set a limit on how many times members can vote per poll.

## Tasks
- [x] Poll limit configuration setting in front-end of #25
- [x] Edit poll limit API
- [x] Poll limit validation in vote API
- [x] Grey out option checkboxes for given poll when limit is reached

## Acceptance Criteria
- [x] Given I am a group owner, I should be able to set or clear the maximum number of votes per user using the page created in #25 .
- [x] Given I am a user, I should be able to vote normally if I haven't exceeded the maximum.
- [x] Given I am a user and I've voted the maximum number of times, I should only be able to remove votes and not add them.
