### ISSUE TITLE
Feature: Archive Event

### ISSUE THREAD

**Issue by elyseyao** [cs130-w22/Group-A1#27]
## User Story
 As an event owner, I want to be able to archive events I own so that they can't be edited anymore.

## Detailed Description
Archived events can still be viewed but should be marked as archived 

## Tasks
- [x] Add event status to event schema/API
- [x] Show event status in event page/event list
- [x] Disable interacting/editing with archived pages on frontend 
- [x] Disable interacting/editing with archived pages on backend

## Acceptance Criteria
- [x] Given I am an event owner, I should be able to archive events I own.
- [x] Given I am an event owner, I should be able to un-archive events I own.
- [x] Given I am an event member, I should not be able to edit or vote on archived events.
- [x] Given I am an event member, I should still be able to view archived events.

**Comment by ultramarathon** [comment]
Work on after pushing Issue 25

**Comment by elyseyao** [comment]
I added a check for archive state to the readOnly state in EventPage, you can consume EventContext in other components to check if the current event shouldn't be able to be interacted with
